version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper  
    restart: unless-stopped  
    ports: ["2181:2181"]

  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports: ["9092:9092"]
    hostname: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka   
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=test_topic:1:1

  producer:
    build: ./services/producer
    restart: unless-stopped
    ports: ["8080:8080"]
    environment:  
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
     
  consumer:
    build: ./services/consumer
    restart: unless-stopped
    ports: ["8081:8081"]
    environment: 
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
