version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "Sending:1:1,Results:1:1"
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      ALLOW_PLAINTEXT_LISTER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEX://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  frontend:
    image: marcado1/sadfrontend
    ports:
    - "3000:3000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_SERVER: kafka:9092
      KEYCLOAK_CLIENTID: service-app
      KEYCLOAK_REALM: sadProject
      KEYCLOAK_SECRET: zHn4WWnbYSywnEIpTFvd74OpPzsYp5w1
      KEYCLOAK_BROKER: keycloak:8080
      KAFKA_ROLE: 

  worker:
    image: marcado1/sadworker
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_SERVER: kafka:9092
      KEYCLOAK_CLIENTID: service-app